# Config file for MCDReforged

# The working directory of the server. If you use default value server/ I will suggest you to put all the files related to the server to the server/ folder
working_directory: server

# The console command to start the server. Examples:
#   java -jar minecraft_server.jar --nogui
#   java -Djline.terminal=jline.UnsupportedTerminal -jar BungeeCord.jar
#   ./start.sh
#   start.bat
start_command: java -jar paperclip-651.jar

# The parser to parse the output of the server. Available options:
# vanilla_parser
#   for vanilla / carpet / fabric server
# paper_parser
#   for paper server
# bungeecord_parser
#   for bungeecord / waterfall server
parser: paper_parser

# the encoding used to encode / decode message to the server. Choose the best encoding for your os. Examples
# utf8
#   for general os
# gbk
#   for Chinese windows user
encoding: gbk

# Debug mode switch. Don't change it to true unless necessary
debug_mode: true
