# Config file for MCDReforged

# The working directory of the server. If you use default value server/ I will suggest you to put all the files related to the server to the server/ folder
working_directory: server


# The console command to start the server. Examples:
#   java -Xms1G -Xmx2G -jar minecraft_server.jar --nogui
#   java -Djline.terminal=jline.UnsupportedTerminal -jar BungeeCord.jar
#   ./start.sh
#   start.bat
start_command: java -Xms1G -Xmx2G -jar minecraft_server.jar --nogui


# The parser to parse the output of the server. Available options:
# vanilla_parser
#   for vanilla / carpet / fabric server
# spigot_parser
#   for spigot 1.14.4+ server
# paper_parser
#   for bukkit / spigot(<=1.13.2) / paper server
# bungeecord_parser
#   for bungeecord server
# waterfall_parser
#   for waterfall server
parser: vanilla_parser


# the encoding / decoding format used to encode / decode message to the server. Choose the best method for your os. Examples:
#   utf8
#   gbk
# leave it blank for MCDR to auto detect system encoding
encoding:
decoding:


# if any command input to the console starts with the string below, MCDR will not send this command to server's stdin
# for example the default value is !! so these commands won't be sent to server's stdin
#   !!test
#   !!this is a command
console_command_prefix: "!!"


# rcon setting
# if enable, plugins can use rcon to query command from the server
enable_rcon: false
rcon_address: 127.0.0.1
rcon_port: 25575
rcon_password: password


# Debug mode switch. Don't change it to true unless necessary
debug_mode: false
