# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Dev build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    name: Test with python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Test with pytest
        run: |
          pytest tests

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Dev Build
      run: |
        mkdir MCDReforged-dev
        mv * MCDReforged-dev || true
        cd MCDReforged-dev
        rm -rf .git
        rm -f %name%.spec .gitignore make_release.bat logo_long.png
        mkdir server
        mkdir config
        cp doc/readme_cn.md .
        rm -f plugins/*
        rm -rf doc
        cd ..
        zip -r MCDReforged-dev.zip ./MCDReforged-dev

    - uses: actions/upload-artifact@v2
      with:
        name: MCDReforged dev build for ${{ github.sha }}
        path: MCDReforged-dev.zip
