name: CI for MCDR

on:
  push:
    paths:
      - ".github/**"
      - "mcdreforged/**"
      - "tests/**"
      - "docker/**"
      - "*.py"

env:
  IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') }}

jobs:
  test:
    uses: ./.github/workflows/test.yml

  assemble:
    needs: test
    uses: ./.github/workflows/assemble.yml

  pypi_upload:
    runs-on: ubuntu-latest
    name: Publish package to (Test)PyPI
    needs: test
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install setuptools wheel

    - name: Create distribution
      id: distribution
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/

    - name: Publish distribution to PyPI
      if: env.IS_RELEASE == 'true'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

    - uses: actions/upload-artifact@v3
      with:
        name: MCDReforged package distribution for ${{ github.sha }}
        path: dist/

    - name: Report PyPI URLs
      run: |
        version=${{ steps.distribution.outputs.version }}
        echo -e "## PyPI Package URLs\n" >> $GITHUB_STEP_SUMMARY
        if [ "$IS_RELEASE" = "true" ]; then
          echo -e "### PyPI\n" >> $GITHUB_STEP_SUMMARY
          echo -e "https://pypi.org/project/mcdreforged/${version}/\n" >> $GITHUB_STEP_SUMMARY
          echo -e "\`\`\`\npip install mcdreforged==$version\n\`\`\`\n" >> $GITHUB_STEP_SUMMARY
        fi
        echo -e "### Test PyPI\n" >> $GITHUB_STEP_SUMMARY
        echo -e "https://test.pypi.org/project/mcdreforged/$version/\n" >> $GITHUB_STEP_SUMMARY
        echo -e "\`\`\`\npip install mcdreforged==$version -r https://test.pypi.org/simple\n\`\`\`\n" >> $GITHUB_STEP_SUMMARY

    outputs:
      version: ${{ steps.distribution.outputs.version }}

  image:
    name: Docker image (py${{ matrix.python }}${{ matrix.slim == 'true' && ', slim' || '' }})
    runs-on: ubuntu-latest
    needs: pypi_upload
    strategy:
      matrix:
        slim: ['false', 'true']
        python: ['3.10', '3.11', '3.12']  # last 3 minor versions

    steps:
    - uses: actions/checkout@v3

    - name: Prepare build config
      uses: actions/github-script@v7
      id: config
      with:
        script: |
          const slim = process.env.SLIM
          const python = process.env.PYTHON
          const isRelease = process.env.IS_RELEASE === 'true'

          if (isRelease) {
            core.setOutput('pypi_simple', 'https://pypi.org/simple')
          } else {
            core.setOutput('pypi_simple', 'https://test.pypi.org/simple')
          }
          
          let metaTagsBase = [
            'type=ref,event=branch,suffix=',
            'type=semver,pattern={{version}}',
            'type=semver,pattern={{major}}.{{minor}}',
          ]
          let metaTagsLatest = []
          let suffixes = [`-py${python}`]  // will be appended at the end of all metaTagsBase

          if (python === '3.11') {  // 3.11 is the default python version
            suffixes.push('')  // add a no-python suffixes
            if (isRelease) {
              metaTagsLatest.push('latest')
            }
          }
          let metaTagsAll = suffixes.flatMap(suffix => metaTagsBase.map(t => t + suffix)).concat(metaTagsLatest)
          console.log(`metaTagsAll 1: ${JSON.stringify(metaTagsAll)}`)
          
          if (slim === 'true') {
            core.setOutput('platforms', 'linux/amd64')
            core.setOutput('base_image_tag', `${python}-slim`)
            metaTagsAll = metaTagsAll.map(item => item + '-slim');
          } else {
            core.setOutput('platforms', 'linux/amd64,linux/arm64')
            core.setOutput('base_image_tag', python)
          }
          console.log(`suffixes: ${JSON.stringify(suffixes)}`)
          
          core.setOutput('tags', metaTagsAll.join('\n'))
          console.log(`metaTagsAll final: ${JSON.stringify(metaTagsAll)}`)
      env:
        SLIM: ${{ matrix.slim }}
        PYTHON: ${{ matrix.python }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: fallenbreath
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: mcdreforged/mcdreforged
        tags: ${{ steps.config.outputs.tags }}
        flavor: latest=false

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Wait for PyPI index update
      run: |
        start_time=$(date +%s)
        while true; do
          if pip3 install "mcdreforged==${VERSION}" -i "${PYPI_SIMPLE}" --dry-run --ignore-installed --no-deps; then
            echo "Version ${VERSION} exists on ${PYPI_SIMPLE}, wait 10s and exit"
            sleep 10
            break
          else
            current_time=$(date +%s)
            elapsed_time=$((current_time - start_time))
            if [ "$elapsed_time" -ge 600 ]; then
              echo "Failed to find package version ${VERSION} on ${PYPI_SIMPLE} after 10 minutes"
              exit 1
            fi
            echo "Version ${VERSION} not exist on ${PYPI_SIMPLE}. Checking again in 5 seconds"
            sleep 5
          fi
        done
      env:
        VERSION: ${{ needs.pypi_upload.outputs.version }}
        PYPI_SIMPLE: ${{ steps.config.outputs.pypi_simple }}

    - name: Build and push
      id: build
      uses: docker/build-push-action@v5
      with:
        platforms: ${{ steps.config.outputs.platforms }}
        push: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' }}
        file: docker/Dockerfile
        context: docker
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BASE_IMAGE_TAG=${{ steps.config.outputs.base_image_tag }}
          MCDR_REQUIREMENT=${{ needs.pypi_upload.outputs.version }}
          PYPI_INDEX=${{ steps.config.outputs.pypi_simple }}

    - name: Prepare extended image build workflow arguments
      uses: actions/github-script@v7
      id: dispatch_args
      with:
        script: |-
          let tags = process.env.TAGS.trim().
              split('\n').
              map(t => t.substring(t.lastIndexOf(':') + 1)).
              join(',')
          core.setOutput('payload', JSON.stringify({
            'base_image_tags': tags,
            'digest': process.env.DIGEST,
            'git_ref': process.env.GITHUB_REF,
            'run_number': process.env.GITHUB_RUN_NUMBER,
          }))
      env:
        TAGS: ${{ steps.meta.outputs.tags }}
        DIGEST: ${{ steps.build.outputs.digest }}

    - name: Trigger extended image builds
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPOSITORY_DISPATCH_PAT }}
        repository: Fallen-Breath/MCDReforged-Docker
        event-type: trigger-workflow
        client-payload: ${{ steps.dispatch_args.outputs.payload }}
